title: Lina Breslav's Portfolio
url: "https://www.linabreslav.com" # the base hostname & protocol for your site
twitter_username: linabreslav
github_username:  linabreslav

# Build settings
markdown: kramdown
