title: Lina Breslav's Portfolio
baseurl: ""
url: "http://www.linabreslav.com" # the base hostname & protocol for your site
twitter_username: linabreslav
github_username:  linabreslav

# Build settings
markdown: kramdown
